### ISSUE TITLE
Installation : gn_module_flore_prioritaire  does not appear to be a Python project

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/gn_module_flore_prioritaire#49]
Version de geonature : 2.13.0
Version de flore prioritaire : 2.2.0

Bonjour,
J'essaie d'installer le module flore prioritaire mais le lancement de la commande install-gn-module me renvoie une erreur lors de l'installation du backend :

```
geonature install-gn-module ~/modules/gn_module_flore_prioritaire PRIORITY_FLORA
/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
  util.warn(
Installation du backend…
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/geoa/modules/gn_module_flore_prioritaire
ERROR: file:///home/geoa/modules/gn_module_flore_prioritaire does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/geoa/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geoa/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/geoa/geonature/backend/geonature/core/command/create_gn_module.py", line 34, in install_gn_module
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geoa/modules/gn_module_flore_prioritaire'' returned non-zero exit status 1.
```
Est-ce que c'est un problème de compatibilité de version ? Je n'ai pas trouvé de n° de version de geonature dans le fichier de release et dans la doc on mentionne la 2.9 mais ici on parle de la toute dernière version de gn : [To 2.13](https://github.com/PnX-SI/gn_module_flore_prioritaire/pull/47)

J'ai essayé de l'installer avec le tuto de la documentation de geonature [installation-d-un-module-geonature](https://docs.geonature.fr/installation.html#installation-d-un-module-geonature) et en suivant celui du module avec le même résultat.

**Comment by TheoLechemia** [comment]
Bonjour,

Le module flore prioritaire n'est pas encore compatible 2.13. La PR : https://github.com/PnX-SI/gn_module_flore_prioritaire/pull/47 est la branche sur laquelle je suis justement en train de travailler pour le rendre compatible 2.13. 
Je ne savais pas que d'autres personnes allait utiliser ce module ... :/ il reste encore un peu de travail pour qu'il soit installable facilement !

**Comment by TheoLechemia** [comment]
Pour info, il s'agit d'un module du réseau flore sentinelle (https://floresentinelle.fr/). Le protocole est vraiment spécifique à ce réseau. Si vous en faite parti, il est plutôt recommandé de saisir directement dans le réseau.
Mais rien n'empêche de l'utiliser !
